from tkinter import *
import math

def selcton():
 sel=   str(var.get())
def clear():
   Ent1.delete(0, 'end')
   Ent2.delete(0, 'end')
   Ent3.delete(0, 'end')
   Ent4.delete(0, 'end')
def cal_dis():
 lat1=float(Ent1.get())
 long1=float(Ent2.get())
 lat2=float(Ent3.get())
 long2=float(Ent4.get())
 p =math.pi/180
 a=0.5-math.cos((lat2-lat1)*p)/2+math.cos(lat1*p)*math.cos(lat2*p)*(1-math.cos((long2-long1)*p))/2
 Chg_long=(long2-long1)
 X= math.sin(math.radians(Chg_long))*math.cos(math.radians(lat2))
 Y= math.cos(math.radians(lat1))*math.sin(math.radians(lat2))-math.sin(math.radians(lat1))*math.cos(math.radians(lat2))*math.cos(math.radians(Chg_long))
 brng=math.radians((math.atan2(X,Y)))
 brng=(360-(brng+360)%360)
 Km =(12742*math.asin((math.sqrt(a))))
 mile=Km*0.621
 Y_format =("The distance in Neutical Miles is:",mile,("Neutical Miles"))
 x_format = ("The distance in Kilometer is:",Km,("Km"))
 z_format= ("The bearing is between two points is :",brng,"radians")
 lb7.insert(0, x_format)
 lb7.insert(0,Y_format)
 lb7.insert(0,z_format)
window= Tk()
window['bg']=""
window.wm_title("GeoDistance Calculator")
window.geometry('550x400')
layer=Label(window,text="NATIONAL CENTER FOR REMOTE SENSING JOS,PLATEAU STATE, NIGERIA. ",font=('Arial',10),bd=20,bg='green')
layer.place(relx=0.01,rely =0.02,relheight=0.08,relwidth=1)
layer2=Label(window,text="DEPARTMENT OF GROUND RECEIVING STATION ",font=('Arial',10),bd=20,bg='yellow')
layer2.place(relx=0.17,rely =0.1,relheight=0.04,relwidth=0.7)
var=IntVar()
lb=Label(window,text= "Select coordiate format")
R1=Radiobutton(window,text='DD',variable=var,value=1,command=selcton)
R1.place(relx=0.12,rely =0.15,relheight=0.05,relwidth=0.15,anchor="n")
lb1=Label(window,text= "First Point")
lb1.place(relx=0.1,rely =0.2,relheight=0.1,relwidth=0.2)
lb2=Label(window,text= "Second Point")
lb2.place(relx=0.65,rely =0.2,relheight=0.1,relwidth=0.2)
lb3=Label(window,text= "Latitude")
lb3.place(relx=0.12,rely =0.3,relheight=0.1,relwidth=0.2,anchor="n")
Ent1=Entry(window)
Ent1.place(relx=0.17,rely =0.32,relheight=0.05,relwidth=0.2)
lb4=Label(window,text= "Longitude")
lb4.place(relx=0.12,rely =0.42,relheight=0.05,relwidth=0.2,anchor="n")
Ent2=Entry(window)
Ent2.place(relx=0.17,rely =0.42,relheight=0.05,relwidth=0.2)
lb5=Label(window,text= "Latitude")
lb5.place(relx=0.5,rely =0.3,relheight=0.1,relwidth=0.2)
Ent3=Entry(window)
Ent3.place(relx=0.65,rely =0.32,relheight=0.05,relwidth=0.2)
lb6=Label(window,text= "Longitude")
lb6.place(relx=0.5,rely =0.42,relheight=0.05,relwidth=0.2)
Ent4=Entry(window)
Ent4.place(relx=0.65,rely =0.42,relheight=0.05,relwidth=0.2)
lb6=Label(window,text= "Select Distance Unit")
lb6.place(relx=0.15,rely =0.52,relheight=0.05,relwidth=0.2,anchor="n")
Ent5=OptionMenu(window,variable='Neutical Mile',value='Neutical Mile')
Ent5.place(relx=0.25,rely =0.52,relheight=0.05,relwidth=0.22)
BT1=Button(window,text= "Calculate Distance",bg='#888',command=cal_dis)
BT1.place(relx=0.7,rely =0.52,relheight=0.05,relwidth=0.2)
BT1=Button(window,text= "clear",bg='#888',command=clear)
BT1.place(relx=0.12,rely =0.62,relheight=0.05,relwidth=0.2,anchor='n')
FR1=Frame(window,bd=5,bg='#888')
FR1.place(relx=0.12,rely =0.72,relheight=0.2,relwidth=0.8)
lb7=Listbox(FR1)
lb7.place(relx=0.5,relheight=1,relwidth=1,anchor="n")
window.mainloop()
